---
- name: install ruby+bundler
  hosts: all
  become: true
  tags: install
  tasks:
  - name: install
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - git
      - ruby-full
      - ruby-bundler
      - build-essential
